### ISSUE TITLE
exceptions

### ISSUE THREAD

**Issue by henryzhang87** [ualbertalib/dvn#4]
After I installed glassfish, and ran the command 

asadmin start-domain

and then checked server.log file. There are no exceptions.

I continued to install dataverse, and then after the starting of the domain, I checked the server.log file. It contained a lot of exceptions, however dataverse is working well. These exception messages just make me feel uncomfortable. I wish we can get rid of these exceptions somehow. Here is server.log 

org.jboss.weld.resources.spi.ResourceLoadingException: Error loading class org.jboss.logging.Slf4jLogger
        at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:152)
        at org.jboss.weld.bootstrap.BeanDeployer.addClass(BeanDeployer.java:86)
        at org.jboss.weld.bootstrap.BeanDeployer.addClasses(BeanDeployer.java:115)
        at org.jboss.weld.bootstrap.BeanDeployment.createBeans(BeanDeployment.java:171)
        at org.jboss.weld.bootstrap.WeldBootstrap.deployBeans(WeldBootstrap.java:336)
        at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:179)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:128)
        at org.glassfish.internal.data.ApplicationInfo.load(ApplicationInfo.java:277)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:460)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.processApplication(ApplicationLoaderService.java:375)
        at com.sun.enterprise.v3.server.ApplicationLoaderService.postConstruct(ApplicationLoaderService.java:219)
        at com.sun.hk2.component.AbstractCreatorImpl.inject(AbstractCreatorImpl.java:131)
        at com.sun.hk2.component.ConstructorCreator.initialize(ConstructorCreator.java:91)
        at com.sun.hk2.component.AbstractCreatorImpl.get(AbstractCreatorImpl.java:82)
        at com.sun.hk2.component.SingletonInhabitant.get(SingletonInhabitant.java:67)
        at com.sun.hk2.component.EventPublishingInhabitant.get(EventPublishingInhabitant.java:139)
        at com.sun.hk2.component.AbstractInhabitantImpl.get(AbstractInhabitantImpl.java:78)
        at com.sun.enterprise.v3.server.AppServerStartup.run(AppServerStartup.java:253)
        at com.sun.enterprise.v3.server.AppServerStartup.doStart(AppServerStartup.java:145)
        at com.sun.enterprise.v3.server.AppServerStartup.start(AppServerStartup.java:136)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishImpl.start(GlassFishImpl.java:79)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishDecorator.start(GlassFishDecorator.java:63)
        at com.sun.enterprise.glassfish.bootstrap.osgi.OSGiGlassFishImpl.start(OSGiGlassFishImpl.java:69)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain$Launcher.launch(GlassFishMain.java:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at com.sun.enterprise.glassfish.bootstrap.GlassFishMain.main(GlassFishMain.java:97)
        at com.sun.enterprise.glassfish.bootstrap.ASMain.main(ASMain.java:55)
Caused by: java.lang.NoClassDefFoundError: Lorg/slf4j/Logger;
        at java.lang.Class.getDeclaredFields0(Native Method)
        at java.lang.Class.privateGetDeclaredFields(Class.java:2300)
        at java.lang.Class.getDeclaredFields(Class.java:1745)
        at org.jboss.weld.util.reflection.SecureReflections$4.work(SecureReflections.java:102)
        at org.jboss.weld.util.reflection.SecureReflections$4.work(SecureReflections.java:99)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.run(SecureReflectionAccess.java:52)
        at org.jboss.weld.util.reflection.SecureReflectionAccess.runAndWrap(SecureReflectionAccess.java:63)
        at org.jboss.weld.util.reflection.SecureReflections.getDeclaredFields(SecureReflections.java:99)
        at org.jboss.weld.introspector.jlr.WeldClassImpl.<init>(WeldClassImpl.java:153)
        at org.jboss.weld.introspector.jlr.WeldClassImpl.of(WeldClassImpl.java:118)
        at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:49)
        at org.jboss.weld.resources.ClassTransformer$TransformTypeToWeldClass.apply(ClassTransformer.java:40)
        at com.google.common.collect.ComputingConcurrentHashMap.compute(ComputingConcurrentHashMap.java:206)
        at com.google.common.collect.ComputingConcurrentHashMap.apply(ComputingConcurrentHashMap.java:100)
        at com.google.common.collect.MapMaker$ComputingMapAdapter.get(MapMaker.java:515)
        at org.jboss.weld.resources.ClassTransformer.loadClass(ClassTransformer.java:149)
        ... 29 more
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
Caused by: java.lang.ClassNotFoundException: org.slf4j.Logger
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1509)
        at org.glassfish.web.loader.WebappClassLoader.loadClass(WebappClassLoader.java:1359)

**Comment by piyapongch** [comment]
I have added dependency libraries, but it failed to deploy. I think this might be conflict on new dependencies that I have added.

**Comment by piyapongch** [comment]
We have decided not to fix this. Because it has happened with any installations that we have known of and it does not have any effect on the process. We will wait and hope that they will fix it in the version 4.
